# Generated by Django 5.1.6 on 2025-02-13 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('start_time', models.CharField(max_length=10)),
                ('finish_time', models.CharField(max_length=10)),
                ('created_ed', models.DateTimeField(auto_now_add=True)),
                ('update_ed', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=50)),
                ('created_ed', models.DateTimeField(auto_now_add=True)),
                ('update_ed', models.DateTimeField(auto_now=True)),
                ('kurs_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configapp.kurs')),
            ],
        ),
    ]
